# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
 default:name

steps:
  - script: echo hello, by azure
    displayName: 'run echo command'
  - script:  mvn clean install
    displayName: 'run maven build'
  - script: java -jar target/m-0.0.1-SNAPSHOT.jar
    displayName: 'run jar file'
